# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0003_auto_20180705_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='parent_company_key',
            new_name='parent_company',
        ),
    ]
