# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_remove_company_parent_company_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent_company_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
