# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0009_auto_20180710_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='parent_company_key',
        ),
    ]
