# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0015_auto_20180710_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company_key',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_dept_key',
            field=models.ForeignKey(blank=True, db_column='parent_dept_key', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.Department', to_field='key'),
        ),
    ]
