# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0016_auto_20180711_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='job_data',
            name='empl_key',
            field=models.ForeignKey(blank=True, db_column='empl_key', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.Employee', to_field='key'),
        ),
    ]
