# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0017_auto_20180713_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_data',
            name='empl_key',
            field=models.ForeignKey(db_column='empl_key', default='', on_delete=django.db.models.deletion.CASCADE, to='mdm.Employee', to_field='key'),
        ),
    ]
