# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0021_auto_20180713_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='job_data',
            name='pos_key',
            field=models.ForeignKey(db_column='pos_key', default='', on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='mdm.Position', to_field='key'),
        ),
        
    ]
