# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0025_job_data_is_main_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('empl_key', models.CharField(max_length=20)),
                ('org_relation_key', models.CharField(max_length=20)),
                ('job_data_key', models.CharField(max_length=20)),
                ('company_key', models.CharField(max_length=20)),
                ('contract_sign_company', models.CharField(max_length=100)),
                ('contract_main_company', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=20)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('seq', models.IntegerField(null=True)),
                ('last_flag', models.CharField(max_length=1, null=True)),
                ('isrefer', models.CharField(max_length=1, null=True)),
                ('effective_flag', models.IntegerField(default=0)),
                ('created_job', models.CharField(blank=True, max_length=100, null=True)),
                ('created_tr', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField()),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='Legal_Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=20, unique=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(default=1)),
                ('effective_flag', models.IntegerField(default=0)),
                ('created_job', models.CharField(blank=True, max_length=100, null=True)),
                ('created_tr', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('parent_company_key', models.ForeignKey(blank=True, db_column='parent_company_key', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.Legal_Entity', to_field='key')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='erp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job_data',
            name='workplace_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_data',
            name='workplace_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_data',
            name='workplace_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_data',
            name='workplace_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_data',
            name='workplace_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='org_relation',
            name='erp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
