# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0025_job_data_is_main_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_data',
            name='workplace_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_data',
            name='workplace_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_data',
            name='workplace_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_data',
            name='workplace_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_data',
            name='workplace_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
