# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0026_auto_20180907_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal_Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=20, unique=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(default=1)),
                ('effective_flag', models.IntegerField(default=0)),
                ('created_job', models.CharField(blank=True, max_length=100, null=True)),
                ('created_tr', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('parent_company_key', models.ForeignKey(blank=True, db_column='parent_company_key', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.Legal_Entity', to_field='key')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
