# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0027_legal_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('empl_key', models.CharField(max_length=20)),
                ('org_relation_key', models.CharField(max_length=20)),
                ('job_data_key', models.CharField(max_length=20)),
                ('company_key', models.CharField(max_length=20)),
                ('contract_sign_company', models.CharField(max_length=100)),
                ('contract_main_company', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=20)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('seq', models.IntegerField(null=True)),
                ('last_flag', models.CharField(max_length=1, null=True)),
                ('isrefer', models.CharField(max_length=1, null=True)),
                ('effective_flag', models.IntegerField(default=0)),
                ('created_job', models.CharField(blank=True, max_length=100, null=True)),
                ('created_tr', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField()),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
