# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0028_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='erp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='org_relation',
            name='erp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
