# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0029_auto_20180921_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='erp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
